"""Generate the page's design tokens from the Nightcrawler design system.

Source: design/tokens.json, a copy of the design system's tokens
(https://claude.ai/artifact/KC3FHaFQPuzeeudMazyF9k, project/tokens.json).
Output: src/nightcrawler/web/tokens.css, the only file of the page allowed to hold
literal colours (WIP-94). Re-run after changing design/tokens.json:

    python scripts/gen_tokens.py            # writes tokens.css
    python scripts/gen_tokens.py --check    # exits 1 if tokens.css is stale
    python scripts/gen_tokens.py --contrast # prints the contrast pairs of docs/DESIGN.md
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "design" / "tokens.json"
TARGET = ROOT / "src" / "nightcrawler" / "web" / "tokens.css"

# Text / background pairs the design system relies on (docs/DESIGN.md).
CONTRAST_PAIRS = [
    ("ink", "ground"),
    ("ink-soft", "ground"),
    ("ink-muted", "ground"),
    ("accent-ink", "ground"),
    ("ink", "accent"),
    ("on-ink", "ink"),
    ("ink", "surface"),
    ("ink-muted", "surface"),
    ("accent", "ground"),
]

# Self-hosted fonts (OFL 1.1, Fontsource 5.3.0 packages): no request to Google's servers.
# Unicode ranges are Fontsource's own "latin" and "latin-ext" subsets.
LATIN = (
    "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,"
    "U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
)
LATIN_EXT = (
    "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,"
    "U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,"
    "U+2C60-2C7F,U+A720-A7FF"
)
FONTS = [
    ("Bricolage Grotesque", "bricolage-grotesque", "opsz", "600 800"),
    ("Hanken Grotesk", "hanken-grotesk", "wght", "400 700"),
]


def _channel(c: float) -> float:
    c /= 255
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def luminance(hex_colour: str) -> float:
    """Relative luminance, WCAG 2.1 definition (https://www.w3.org/TR/WCAG21/#dfn-relative-luminance)."""
    h = hex_colour.lstrip("#")
    r, g, b = (int(h[i : i + 2], 16) for i in (0, 2, 4))
    return 0.2126 * _channel(r) + 0.7152 * _channel(g) + 0.0722 * _channel(b)


def contrast(fg: str, bg: str) -> float:
    """Contrast ratio, WCAG 2.1 definition (https://www.w3.org/TR/WCAG21/#dfn-contrast-ratio)."""
    a, b = sorted((luminance(fg), luminance(bg)), reverse=True)
    return (a + 0.05) / (b + 0.05)


def load(path: Path = SOURCE) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def colours(tokens: dict) -> dict[str, str]:
    return {t["name"]: t["value"] for t in tokens["color"]["tokens"]}


def render(tokens: dict) -> str:
    out = [
        "/* Generated by scripts/gen_tokens.py from design/tokens.json. Do not edit by hand.",
        "   Design system: https://claude.ai/artifact/KC3FHaFQPuzeeudMazyF9k (see docs/DESIGN.md).",
        "   The only file of the page with literal colours (WIP-94). */",
        "",
    ]
    for family, slug, axis, weights in FONTS:
        for subset, rng in (("latin", LATIN), ("latin-ext", LATIN_EXT)):
            out += [
                "@font-face {",
                f'  font-family: "{family}";',
                "  font-style: normal;",
                "  font-display: swap;",
                f"  font-weight: {weights};",
                f'  src: url("fonts/{slug}-{subset}-{axis}-normal.woff2") format("woff2");',
                f"  unicode-range: {rng};",
                "}",
            ]
    out += ["", ":root {", "  color-scheme: light;"]
    for t in tokens["color"]["tokens"]:
        out.append(f"  --{t['name']}: {t['value'].lower()};")
    for key, prefix in (("display", "font-display"), ("body", "font-body")):
        out.append(f"  --{prefix}: {tokens['type']['families'][key]};")
    for group in ("spacing", "radius", "size"):
        for t in tokens[group]["tokens"]:
            out.append(f"  --{t['name']}: {t['value']};")
    out.append("}")
    return "\n".join(out) + "\n"


def contrast_table(tokens: dict) -> list[tuple[str, str, float]]:
    c = colours(tokens)
    return [(fg, bg, round(contrast(c[fg], c[bg]), 1)) for fg, bg in CONTRAST_PAIRS]


def main(argv: list[str]) -> int:
    tokens = load()
    css = render(tokens)
    if "--contrast" in argv:
        for fg, bg, ratio in contrast_table(tokens):
            print(f"| `{fg}` on `{bg}` | {ratio}:1 |")
        return 0
    if "--check" in argv:
        if TARGET.read_text(encoding="utf-8") != css:
            print("tokens.css is stale: run python scripts/gen_tokens.py", file=sys.stderr)
            return 1
        return 0
    TARGET.write_text(css, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
